apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
  template:
    metadata:
      labels:
        app: metallb
    spec:
      containers:
        - name: controller
          image: metallb/controller:0.14.9
          args:
            - --log-level=info
            - --port=7472
            - --config=config
